// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeKare.Api.Data;

#nullable disable

namespace PrimeKare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820095310_UpdateCustomersVehiclesServicesUsersSchemas")]
    partial class UpdateCustomersVehiclesServicesUsersSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimeKare.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PrimeKare.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(6506),
                            Description = "Engine oil and oil filter replacement.",
                            EstimatedMinutes = 45,
                            IsActive = true,
                            Name = "Oil Change",
                            Price = 89.90m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(6510)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8238),
                            Description = "Brake inspection, repair and replacement.",
                            EstimatedMinutes = 90,
                            IsActive = true,
                            Name = "Brake Service",
                            Price = 150.00m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8239)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8242),
                            Description = "Computerized engine diagnostics and inspection.",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            Name = "Engine Diagnostics",
                            Price = 120.00m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8242)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8243),
                            Description = "Tyre inspection, replacement and balancing.",
                            EstimatedMinutes = 45,
                            IsActive = true,
                            Name = "Tyre Service",
                            Price = 80.00m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8244)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8245),
                            Description = "Battery testing and replacement service.",
                            EstimatedMinutes = 30,
                            IsActive = true,
                            Name = "Battery Replacement",
                            Price = 180.00m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8245)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8246),
                            Description = "Air conditioning inspection and servicing.",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            Name = "Air Conditioning",
                            Price = 100.00m,
                            UpdatedAt = new DateTime(2026, 8, 20, 9, 53, 7, 354, DateTimeKind.Utc).AddTicks(8247)
                        });
                });

            modelBuilder.Entity("PrimeKare.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrimeKare.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("PrimeKare.Api.Models.User", b =>
                {
                    b.HasOne("PrimeKare.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PrimeKare.Api.Models.Vehicle", b =>
                {
                    b.HasOne("PrimeKare.Api.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PrimeKare.Api.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
