stages:
  - build
  - test

frontend_build:
  stage: build
  image: node:22

  script:
    - cd frontend
    - npm ci
    - npm run build

backend_build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0

  script:
    - cd backend/dev/PrimeKare.Api
    - dotnet restore
    - dotnet build --no-restore

backend_test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0

  script:
    - cd backend/PrimeKare.Api.Tests
    - dotnet test