name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # frontend_build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v5
  #       with:
  #         node-version: 22

  #     - name: Install dependencies
  #       working-directory: frontend
  #       run: npm ci

  #     - name: Build frontend
  #       working-directory: frontend
  #       run: npm run build

  backend_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        working-directory: backend/PrimeKare.Api
        run: dotnet restore

      - name: Build
        working-directory: backend/PrimeKare.Api
        run: dotnet build --no-restore

  backend_test:
    needs:
      # - frontend_build
      - backend_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Create Firebase credentials
        working-directory: backend/PrimeKare.Api
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Run backend tests
        working-directory: backend/PrimeKare.Api.Tests
        env:
          UseInMemoryDatabase: "true"
          Jwt__Key: ${{ secrets.JWT_KEY }}
          Firebase__CredentialPath: ../PrimeKare.Api/firebase-service-account.json
        run: dotnet test
