// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeKare.Api.Data;

#nullable disable

namespace PrimeKare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810052658_SeedServices")]
    partial class SeedServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimeKare.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Engine oil and oil filter replacement.",
                            EstimatedMinutes = 45,
                            IsActive = true,
                            Name = "Oil Change",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Brake inspection, repair and replacement.",
                            EstimatedMinutes = 90,
                            IsActive = true,
                            Name = "Brake Service",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Computerized engine diagnostics and inspection.",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            Name = "Engine Diagnostics",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tyre inspection, replacement and balancing.",
                            EstimatedMinutes = 45,
                            IsActive = true,
                            Name = "Tyre Service",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Battery testing and replacement service.",
                            EstimatedMinutes = 30,
                            IsActive = true,
                            Name = "Battery Replacement",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Air conditioning inspection and servicing.",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            Name = "Air Conditioning",
                            Price = 100.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
